### ISSUE TITLE
Private repositories seem unreachable

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_depup#30]
## Is your feature request related to a problem? Please describe.

I have, in my `rebar.config`, references to non-public (i.e. non GitHub, ... and non Hex) Git repositories. `rebar3_hank` can't seem to reach them. It also finishes execution without error/warning messages.

## Describe the solution you'd like

At a first stage, I'd like to have a clear error/warning message stating a given repository was unreachable (but have `rebar3_deps` continue for other repositories).
At a second stage, I'd like to have those repo.s be reachable.
(if this problem is already known, a `README.md` update might be "enough" for now)

## Describe alternatives you've considered

I comment out the entries in the `rebar.config` file, run `rebar3 update-deps` and then remove the comments (and check the versions manually, as I did prior to using the plugin).

**Comment by elbrujohalcon** [comment]
Can you provide a sample rebar.config? The tool is certainly unprepared for that because I don't use such things in my projects.

**Comment by paulo-ferraz-oliveira** [comment]
As I was preparing an example for this, I set up a local Git server and stuff seems to work. I'm now looking (with `rebar3_depup` in `_checkouts`) at a particular server I'm using to check what might be the detail that makes it "not work".

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I see it now. The repo really is "unreachable" (as per the title) network-wise. So I guess what might be missing is a warning of some kind. I'll pull request and let you decide.

**Comment by paulo-ferraz-oliveira** [comment]
`DIAGNOSTIC=1 rebar3 update-deps` returns

```
failed with return code 128 and the following output:
ssh: connect to host <HOST> port <PORT>: Network is unreachable
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by paulo-ferraz-oliveira** [comment]
In the call to `rebar_utils:sh` we could use option `use_stdout` which outputs to stdout in case of error, and also stops the process, as-is. In this case, we do have more info. for the consumer.

**Comment by paulo-ferraz-oliveira** [comment]
This is way too verbose when there's a lot of tags involved... Not a real issue if used in CI, but if used locally can generate a lot of noise.

**Comment by paulo-ferraz-oliveira** [comment]
I'm preparing a pull request to be less verbose but still attack the current issue.
